architecture:
  frequency: 600
  core_num: 16
  core:
    controller:
      power: 1.0
      area: 1.0
    matrix:
      mac_num: 128
      power: 1.1
      area: 1.1
    vector:
      vec_num: 8
      power: 1.2
      area: 1.2
    buffer:
      buffer_size: 38
      read_bw: 8192
      write_bw: 8192
      power: 1.3
      area: 1.3
  dram:
    config_path: configs/architecture/dram/hb_dram_edge.yaml
    power: 1.4
    area: 1.4
