architecture:
  frequency: 1000
  core_num: 16
  core:
    controller:
      power: 0.7250
      area: 3.6650
    matrix:
      mac_num: 5376
      power: 2.1875
      area: 9.1878
    vector:
      vec_num: 336
      power: 0.2636
      area: 0.8750
    buffer:
      buffer_size: 2048
      read_bw: 32768.0
      write_bw: 32768.0
      power: 5.0869
      area: 15.2101
  dram:
    config_path: configs/architecture/dram/cloud/cloud_2TBps.yaml
    power: 12.2360
    area: 10.0450
  noc:
    topology: mesh
    config_path: configs/architecture/noc/4x4_mesh
    flit_size: 64
    power: 0.2636
    area: 3.4236
