architecture:
  frequency: 1000
  core_num: 16
  core:
    controller:
      power: 0.7250
      area: 3.6650
    matrix:
      mac_num: 7680
      power: 3.1250
      area: 13.1255
    vector:
      vec_num: 240
      power: 0.1883
      area: 0.6250
    buffer:
      buffer_size: 2048
      read_bw: 32768.0
      write_bw: 32768.0
      power: 5.0869
      area: 15.2101
  dram:
    config_path: configs/architecture/dram/cloud/cloud_0.5TBps.yaml
    power: 2.6680
    area: 2.4990
  noc:
    topology: mesh
    config_path: configs/architecture/noc/4x4_mesh
    flit_size: 256
    power: 0.8990
    area: 12.9438
