communication:
  on_chip:
    - tx:
        buffer_load:
        noc:
      rx:
        buffer_load:
          - name: reduce1_load
            byte_count: 32768
            is_write: false
        buffer_store:
          - name: noc_rx1_store
            byte_count: 16384
            is_write: true
          - name: reduce1_store
            byte_count: 16384
            is_write: true
        vector:
          - name: reduce1
            vec_count: 16384
        noc:
          - name: noc_rx1
            is_send: false
            src: 1
            dst: 5
            flit_num: 256
            init_flit_id: 0

    - tx:
        buffer_load:
          - name: noc_tx9_load
            byte_count: 16384
            is_write: false
        noc:
          - name: noc_tx9
            is_send: true
            src: 5
            dst: 9
            flit_num: 256
            init_flit_id: 0
      rx:
        buffer_load:
          - name: reduce1_load
            byte_count: 32768
            is_write: false
          - name: reduce9_load
            byte_count: 32768
            is_write: false
        buffer_store:
          - name: noc_rx1_store
            byte_count: 16384
            is_write: true
          - name: reduce1_store
            byte_count: 16384
            is_write: true
          - name: noc_rx9_store
            byte_count: 16384
            is_write: true
          - name: reduce9_store
            byte_count: 16384
            is_write: true
        vector:
          - name: reduce1
            vec_count: 16384
          - name: reduce9
            vec_count: 16384
        noc:
          - name: noc_rx1
            is_send: false
            src: 1
            dst: 5
            flit_num: 256
            init_flit_id: 256
          - name: noc_rx9
            is_send: false
            src: 9
            dst: 5
            flit_num: 256
            init_flit_id: 0

    - tx:
        buffer_load:
          - name: noc_tx1_load
            byte_count: 16384
            is_write: false
          - name: noc_tx9_load
            byte_count: 16384
            is_write: false
        noc:
          - name: noc_tx1
            is_send: true
            src: 5
            dst: 1
            flit_num: 256
            init_flit_id: 256
          - name: noc_tx9
            is_send: true
            src: 5
            dst: 9
            flit_num: 256
            init_flit_id: 512
      rx:
        buffer_load:
          - name: reduce2_load
            byte_count: 32768
            is_write: false
          - name: reduce9_load
            byte_count: 32768
            is_write: false
        buffer_store:
          - name: noc_rx1_store
            byte_count: 16384
            is_write: true
          - name: reduce1_store
            byte_count: 16384
            is_write: true
          - name: noc_rx9_store
            byte_count: 16384
            is_write: true
          - name: reduce9_store
            byte_count: 16384
            is_write: true
        vector:
          - name: reduce1
            vec_count: 16384
          - name: reduce9
            vec_count: 16384
        noc:
          - name: noc_rx1
            is_send: false
            src: 1
            dst: 5
            flit_num: 256
            init_flit_id: 512
          - name: noc_rx9
            is_send: false
            src: 9
            dst: 5
            flit_num: 256
            init_flit_id: 256

    - tx:
        buffer_load:
          - name: noc_tx1_load
            byte_count: 16384
            is_write: false
          - name: noc_tx9_load
            byte_count: 16384
            is_write: false
        noc:
          - name: noc_tx1
            is_send: true
            src: 5
            dst: 1
            flit_num: 256
            init_flit_id: 768
          - name: noc_tx9
            is_send: true
            src: 5
            dst: 9
            flit_num: 256
            init_flit_id: 1024
      rx:
        buffer_load:
          - name: reduce1_load
            byte_count: 32768
            is_write: false
          - name: reduce9_load
            byte_count: 32768
            is_write: false
        buffer_store:
          - name: noc_rx1_store
            byte_count: 16384
            is_write: true
          - name: reduce1_store
            byte_count: 16384
            is_write: true
          - name: noc_rx9_store
            byte_count: 16384
            is_write: true
          - name: reduce9_store
            byte_count: 16384
            is_write: true
        vector:
          - name: reduce1
            vec_count: 16384
          - name: reduce9
            vec_count: 16384
        noc:
          - name: noc_rx1
            is_send: false
            src: 1
            dst: 5
            flit_num: 256
            init_flit_id: 768
          - name: noc_rx9
            is_send: false
            src: 9
            dst: 5
            flit_num: 256
            init_flit_id: 768

    - tx:
        buffer_load:
          - name: noc_tx1_load
            byte_count: 16384
            is_write: false
          - name: noc_tx9_load
            byte_count: 16384
            is_write: false
        noc:
          - name: noc_tx1
            is_send: true
            src: 5
            dst: 1
            flit_num: 256
            init_flit_id: 1280
          - name: noc_tx9
            is_send: true
            src: 5
            dst: 9
            flit_num: 256
            init_flit_id: 1536
      rx:
        buffer_load:
          - name: reduce9_load
            byte_count: 32768
            is_write: false
        buffer_store:
          - name: noc_rx9_store
            byte_count: 16384
            is_write: true
          - name: reduce9_store
            byte_count: 16384
            is_write: true
        vector:
          - name: reduce9
            vec_count: 16384
        noc:
          - name: noc_rx9
            is_send: false
            src: 9
            dst: 5
            flit_num: 256
            init_flit_id: 1280

    - tx:
        buffer_load:
          - name: noc_tx1_load
            byte_count: 16384
            is_write: false
        noc:
          - name: noc_tx1
            is_send: true
            src: 5
            dst: 1
            flit_num: 256
            init_flit_id: 1792
      rx:
        buffer_load:
        buffer_store:
        vector:
        noc:

  dram:
    - name: output
      is_write: false
      access_base: [0, 0]
      access_extent: [16, 512]
      access_stride_add: [1, 1]
      access_offset_add: [16, 512]
      init_iter: 0
      stride_iter: 1
      total_iter: 2

    - name: output
      is_write: false
      access_base: [0, 1536]
      access_extent: [16, 512]
      access_stride_add: [1, 1]
      access_offset_add: [16, 1536]
      init_iter: 1
      stride_iter: 1
      total_iter: 2
    
    - name: input
      is_write: true
      access_base: [0, 1024]
      access_extent: [16, 512]
      access_stride_add: [1, 1]
      access_offset_add: [16, 512]
      init_iter: 4
      stride_iter: 1
      total_iter: 2
    
    - name: input
      is_write: true
      access_base: [0, 512]
      access_extent: [16, 512]
      access_stride_add: [1, 1]
      access_offset_add: [16, 1536]
      init_iter: 5
      stride_iter: 1
      total_iter: 2
