architecture:
  frequency: 1000
  core_num: 16
  core:
    controller:
      power: 0.7250
      area: 3.6650
    matrix:
      mac_num: 3584
      power: 1.4583
      area: 6.1252
    vector:
      vec_num: 224
      power: 0.1757
      area: 0.5833
    buffer:
      buffer_size: 16384
      read_bw: 16384.0
      write_bw: 16384.0
      power: 3.1826
      area: 21.3542
  dram:
    config_path: configs/architecture/dram/cloud/cloud_1TBps.yaml
    power: 5.3330
    area: 4.9980
  noc:
    topology: mesh
    config_path: configs/architecture/noc/4x4_mesh
    flit_size: 128
    power: 0.4754
    area: 6.5970
