//===========================================================================
// tb_dot_unit -- self-checking cosimulation of atlas_dot_unit against the
// Python golden model in tb/golden/atlas_fp.py.
//
// Stimulus and expected results come from dot_vectors.txt (generated by
// tb/golden/gen_dot_vectors.py).  Vectors are streamed back to back, so this
// also proves the pipeline sustains one MX block per cycle with no bubbles.
//
// Inputs are driven on the negative edge and the DUT samples on the positive
// edge, so there is no race between stimulus and capture.
//===========================================================================
`timescale 1ns/1ps

module tb_dot_unit;

  localparam int unsigned N       = 32;
  localparam int unsigned MAXV    = 8192;
  localparam int unsigned LATENCY = 4;

  logic clk = 1'b0, rst_n = 1'b0;
  always #0.5 clk = ~clk;

  logic           in_valid;
  logic [1:0]     fmt_a, fmt_b;
  logic [N*8-1:0] a_codes, b_codes;
  logic [7:0]     scale_a, scale_b;
  logic           out_valid;
  logic [31:0]    out_f32;

  atlas_dot_unit #(.N(N)) dut (
    .clk(clk), .rst_n(rst_n),
    .in_valid(in_valid), .fmt_a(fmt_a), .fmt_b(fmt_b),
    .a_codes(a_codes), .b_codes(b_codes),
    .scale_a(scale_a), .scale_b(scale_b),
    .out_valid(out_valid), .out_f32(out_f32)
  );

  int             v_fa [0:MAXV-1];
  int             v_fb [0:MAXV-1];
  logic [7:0]     v_sa [0:MAXV-1];
  logic [7:0]     v_sb [0:MAXV-1];
  logic [N*8-1:0] v_a  [0:MAXV-1];
  logic [N*8-1:0] v_b  [0:MAXV-1];
  logic [31:0]    v_exp[0:MAXV-1];

  int nvec = 0, i_out = 0, errors = 0;

  // ---------------- checker: sample results in issue order ----------------
  always @(posedge clk) begin
    if (rst_n && out_valid) begin
      if (out_f32 !== v_exp[i_out]) begin
        errors <= errors + 1;
        if (errors < 8)
          $display("  MISMATCH vec=%0d fmt=%0d/%0d sa=%02x sb=%02x got=%08x exp=%08x",
                   i_out, v_fa[i_out], v_fb[i_out], v_sa[i_out], v_sb[i_out],
                   out_f32, v_exp[i_out]);
      end
      i_out <= i_out + 1;
    end
  end

  // ---------------- stimulus ----------------
  int    fd, code, i;
  string fname;

  initial begin
    in_valid = 1'b0; fmt_a = '0; fmt_b = '0;
    a_codes  = '0;   b_codes = '0; scale_a = '0; scale_b = '0;

    if (!$value$plusargs("vectors=%s", fname)) fname = "tb/sv/dot_vectors.txt";
    fd = $fopen(fname, "r");
    if (fd == 0) begin
      $display("TB ERROR: cannot open %s", fname);
      $fatal(1);
    end
    code = 7;
    while ((nvec < MAXV) && (code == 7)) begin
      code = $fscanf(fd, "%d %d %h %h %h %h %h",
                     v_fa[nvec], v_fb[nvec], v_sa[nvec], v_sb[nvec],
                     v_a[nvec], v_b[nvec], v_exp[nvec]);
      if (code == 7) nvec = nvec + 1;
    end
    $fclose(fd);
    $display("tb_dot_unit: loaded %0d vectors from %s", nvec, fname);

    repeat (4) @(negedge clk);
    rst_n = 1'b1;

    for (i = 0; i < nvec; i = i + 1) begin
      @(negedge clk);
      in_valid = 1'b1;
      fmt_a    = v_fa[i][1:0];
      fmt_b    = v_fb[i][1:0];
      scale_a  = v_sa[i];
      scale_b  = v_sb[i];
      a_codes  = v_a[i];
      b_codes  = v_b[i];
    end
    @(negedge clk);
    in_valid = 1'b0;

    repeat (LATENCY + 4) @(negedge clk);

    if (i_out != nvec)
      $display("TB ERROR: issued %0d blocks, observed %0d results", nvec, i_out);
    if ((errors == 0) && (i_out == nvec))
      $display("TB_DOT_UNIT: PASS  (%0d vectors, 0 mismatches)", nvec);
    else
      $display("TB_DOT_UNIT: FAIL  (%0d vectors, %0d mismatches)", nvec, errors);
    $finish;
  end

endmodule
