architecture:
  frequency: 1000
  core_num: 16
  core:
    controller:
      power: 0.7250
      area: 3.6650
    matrix:
      mac_num: 7680
      power: 3.1250
      area: 13.1255
    vector:
      vec_num: 480
      power: 0.3766
      area: 1.2500
    buffer:
      buffer_size: 4096
      read_bw: 32768.0
      write_bw: 32768.0
      power: 5.0869
      area: 15.7843
  dram:
    config_path: configs/architecture/dram/cloud/cloud_1TBps.yaml
    power: 5.3330
    area: 4.9980
  noc:
    topology: mesh
    config_path: configs/architecture/noc/4x4_mesh
    flit_size: 64
    power: 0.2636
    area: 3.4236
