operator:
  # per core's shape: (16,2048)*(2048,2048)=(16,2048), per tile: (16,256)*(256,256)=(16,256)
  # output stationary, only split along two hidden dims, each is split evenly to 16 tiles
  # each element is 2 byte
  - name: gemm_example 
    type: gemm
    iteration: 64
    execution:
      matrix:
        - name: gemm_tile
          mac_count: 1048576
      vector:
        - name: gemm_tile_accumulation
          vec_count: 4096
      buffer_load:
        - name: gemm_tile_load
          byte_count: 139264 # 2*(16*256 + 256*256)
          is_write: false 
      buffer_store:
        - name: gemm_tile_store
          byte_count: 8192 # 2*(16*256)
          is_write: true 
      dram:
        - name: input
          is_write: false
          access_base: [0, 0]
          access_extent: [16, 256]
          access_stride_add: [1, 1]
          access_offset_add: [16, 256]
          init_iter: 0
          stride_iter: 1
          total_iter: 256

        - name: weight
          is_write: false
          access_base: [0, 0]
          access_extent: [256, 256]
          access_stride_add: [1, 16]
          access_offset_add: [256, 256]
          init_iter: 0
          stride_iter: 1
          total_iter: 256

        - name: output
          is_write: true
          access_base: [0, 0]
          access_extent: [16, 256]
          access_stride_add: [1, 16]
          access_offset_add: [16, 256]
          init_iter: 17
          stride_iter: 16
          total_iter: 16
