#!/usr/bin/env bash
#
# Static timing analysis of a synthesised ATLAS block with OpenSTA.
#
#   usage: sta/run_sta.sh <top-module> [period_ns] [tech]
#
# Reads the gate netlist produced by syn/run_synth.sh, applies
# sta/scripts/atlas.sdc, and writes a full timing/power report to
# sta/out/<top>_<tech>.rpt.  Exits non-zero if the design misses timing.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STA_BIN="${STA_BIN:-/home/user/OpenSTA/build/sta}"

TOP="${1:?usage: run_sta.sh <top> [period_ns] [tech]}"
PERIOD_NS="${2:-1.0}"
TECH="${3:-asap7}"

OUT="$ROOT/sta/out"; mkdir -p "$OUT"
RPT="$OUT/${TOP}_${TECH}.rpt"
TCL="$OUT/${TOP}_${TECH}.tcl"
NETLIST="$ROOT/syn/out/${TOP}_${TECH}.v"

[[ -f "$NETLIST" ]] || { echo "missing netlist: $NETLIST (run syn/run_synth.sh first)" >&2; exit 1; }

case "$TECH" in
  asap7)
    LIBS=("$ROOT/syn/lib/asap7_simple.lib" "$ROOT/syn/lib/asap7_seq.lib" "$ROOT/syn/lib/asap7_invbuf.lib")
    DRIVE_CELL="BUFx2_ASAP7_75t_R"; DRIVE_PIN="Y"; LOAD_FF="5.0" ;;
  sky130)
    LIBS=("$ROOT/syn/lib/sky130hd_tt.lib")
    DRIVE_CELL="sky130_fd_sc_hd__buf_2"; DRIVE_PIN="X"; LOAD_FF="10.0" ;;
  *) echo "unknown tech: $TECH" >&2; exit 1 ;;
esac

{
  echo "# generated by sta/run_sta.sh -- do not edit"
  for l in "${LIBS[@]}"; do echo "read_liberty $l"; done
  # read_liberty resets the command units to whatever the library declares, so
  # this has to come after it or the SDC period is read in the library's unit
  # (ASAP7 declares ps, which would silently make a 1 ns clock a 1 ps clock).
  echo "set_cmd_units -time ns -capacitance fF -resistance kOhm -voltage V -current mA -power mW -distance um"
  echo "read_verilog $NETLIST"
  echo "link_design $TOP"
  echo "set CLK_PERIOD_NS $PERIOD_NS"
  echo "set DRIVE_CELL $DRIVE_CELL"
  echo "set DRIVE_PIN  $DRIVE_PIN"
  echo "set LOAD_FF    $LOAD_FF"
  echo "source $ROOT/sta/scripts/atlas.sdc"
  cat <<'TCLEOF'

puts "=========================================================="
puts "  ATLAS static timing analysis"
puts "=========================================================="
report_units
puts "\n---------- clocks ----------"
report_clock_properties

puts "\n---------- setup (max) : critical path ----------"
report_checks -path_delay max -group_count 3 -digits 4

puts "\n---------- hold (min) : critical path ----------"
report_checks -path_delay min -group_count 3 -digits 4

puts "\n---------- slack summary ----------"
puts [format "setup WNS : %s ns" [sta::format_time [sta::worst_slack_cmd "max"] 4]]
puts [format "hold  WNS : %s ns" [sta::format_time [sta::worst_slack_cmd "min"] 4]]
report_tns
report_wns

puts "\n---------- design rule checks ----------"
report_check_types -max_slew -max_capacitance -max_fanout -violators

puts "\n---------- power ----------"
report_power -digits 4

set slack [sta::worst_slack_cmd "max"]
if { $slack < 0 } {
  puts "\nRESULT: TIMING NOT MET (setup WNS [sta::format_time $slack 4] ns)"
} else {
  puts "\nRESULT: TIMING MET (setup WNS [sta::format_time $slack 4] ns)"
}
TCLEOF
} > "$TCL"

"$STA_BIN" -no_init -no_splash -exit "$TCL" 2>&1 | tee "$RPT"
echo
echo "report: $RPT"
grep -q "RESULT: TIMING MET" "$RPT"
