#ifndef _ATLASIM_SAMPLE_H
#define _ATLASIM_SAMPLE_H

#include <vector>
#include <random>
#include <iostream>
#include <unordered_set>
#include <algorithm>


namespace atlasim {


// Sample count unique numbers from interval [begin, end)
template<typename T>
std::vector<T> sample_unique(T begin, T end, int count, int seed = -1, bool shuffle = true) {
    if(count < 0) {
        std::cerr << "Sample count must be non-negative." << std::endl;
        exit(-1);
    }
    T n = end-begin;
    if(n < count) {
        std::cerr << "Interval range is less than sample count." << std::endl;
        exit(-1);
    }

    std::vector<T> result;
    result.reserve(count);

    std::mt19937 gen;
    if(seed >= 0) {
        gen.seed(seed);
    }
    else {
        std::random_device rd;
        gen.seed(rd());
    }

    // Use Floyd's sampling algorithm
    std::unordered_set<T> selected;
    for(T i=n-count; i<n; ++i) {
        std::uniform_int_distribution<T> dis(0, i);
        T t = dis(gen);
        if(selected.find(t) == selected.end()) {
            selected.insert(t);
            result.push_back(begin+t);
        }
        else {
            selected.insert(i);
            result.push_back(begin+i);
        }
    }

    // The set generated by Floyd's algorithm is random, but the order may have specific patterns. Shuffle to ensure random permutation
    if(shuffle) {
        std::shuffle(result.begin(), result.end(), gen);
    }

    return result;
}


}


#endif
